// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcGSXp6YiP7GumFergff4F3D7RulI7QTE',
    appId: '1:871114411958:web:e9ccf7cb54f8dd33d9bb17',
    messagingSenderId: '871114411958',
    projectId: 'dine-ease-63a1b',
    authDomain: 'dine-ease-63a1b.firebaseapp.com',
    storageBucket: 'dine-ease-63a1b.appspot.com',
    measurementId: 'G-6T6TS6FHL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1mgrh2wSLldaIxJr57hMwrwTPieu9yto',
    appId: '1:871114411958:android:a73d01336b1a74d7d9bb17',
    messagingSenderId: '871114411958',
    projectId: 'dine-ease-63a1b',
    storageBucket: 'dine-ease-63a1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV3W1PU2d4J8Ue4EXMGVPBQVjE49HGKAw',
    appId: '1:871114411958:ios:bd1a929f99a4ad3cd9bb17',
    messagingSenderId: '871114411958',
    projectId: 'dine-ease-63a1b',
    storageBucket: 'dine-ease-63a1b.appspot.com',
    iosBundleId: 'com.atees.dineEase',
  );
}
